PROJ=special_main

CC=gcc

OBJ=special.o 
#OBJ=least_squares.o khm_common.o 

#CFLAGS=-I /Users/khmacdonald/code/common  -lm
CFLAGS=-I /Users/khmacdonald/code/common  

$(PROJ): $(OBJ)
	$(CC) -g -o $(PROJ) $(PROJ).c $(OBJ) $ $(CFLAGS)

clean: 
	rm $(PROJ) $(OBJ)

