PROJ=bit_main

CC=gcc

OBJ=bit_twiddle.o 
#OBJ=least_squares.o khm_common.o 

CFLAGS=-I /Users/khmacdonald/code/common  -lm

$(PROJ): $(OBJ)
	$(CC) -g -o $(PROJ) $(PROJ).c $(OBJ) $ $(CFLAGS)

clean: 
	rm $(PROJ) $(OBJ)

